version: 2
updates:
    - package-ecosystem: gradle
      directory: "/"
      schedule:
          interval: weekly
          day: monday
          time: "04:30"
          timezone: "Europe/Oslo"
      open-pull-requests-limit: 10
      groups:
          spring:
              patterns:
                  - "org.springframework*"
          platform-and-tooling:
              patterns:
                  - "org.jetbrains.kotlin*"
                  - "com.github.ben-manes.versions"
                  - "org.gradle.toolchains.foojay-resolver-convention"
                  - "org.jlleitschuh.gradle.ktlint"
          minor-and-patch:
              patterns:
                  - "*"
              update-types:
                  - minor
                  - patch
      ignore:
          - dependency-name: "jvm"
          - dependency-name: "plugin.spring"
          - dependency-name: "org.springframework.boot:spring-boot-dependencies"
            update-types: ["version-update:semver-major"]
    - package-ecosystem: docker
      directory: "/"
      schedule:
          interval: weekly
          day: monday
          time: "04:30"
          timezone: "Europe/Oslo"
      open-pull-requests-limit: 5
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: weekly
          day: monday
          time: "04:30"
          timezone: "Europe/Oslo"
      groups:
          github-actions:
              patterns:
                  - "*"
